---
## Ansible Host File

all:
  children:
    AOSCX_Switches:
      hosts:
        swTony:
          # FQDN defined in Ubuntu OS /etc/hosts file
          ansible_host : swTony.newhope.io  
          # ansible_host : 192.168.244.115

        # Ansible will refer (search) for each node file in the host_vars directory   
        swCassidy:   
        swDiego:  
        swJohn:
             
            