---
# Demonstrates the use of the Aruba module to configure a switch.
# Only one command will be ran.
# 
# This playbook uses the "community.network.aruba_config" module to 
# push a simple single configuration, of an NTP server, to the Aruba 
# switch. 
#
# NOTE: Remember that for the aoscx_config module to work successfuly,
#       the default setting "ansible_connection: network_cli" must be
#       uncommented in the all.yml file.


- hosts: AOSCX_Switches
  gather_facts : False
  collections:
    - arubanetworks.aoscx

  tasks:
  - name: Configure NTP server
    #community.network.aruba_config:
    aoscx_config:
      lines: ntp server 1.1.1.1
      