---
# This playbook demonstrates the use of two plays. One play for the REST API
# Aruba "aoscx_banner" module and the other play for the SSH/CLI "aoscx_config"
# module.  
# 
# 1) Create a banner via REST API
# 2) Configure a single NTP server via SSH/CLI
#


- hosts: AOSCX_Switches
  gather_facts : False
  collections:
    - arubanetworks.aoscx
  roles:
    - role: arubanetworks.aoscx_role

  tasks:
    - name: Create a banner on switch
      aoscx_banner:
        banner_type: banner     # Creating banner motd
        banner: | 

          ░█████╗░░█████╗░░██████╗░██████╗██╗██████╗░██╗░░░██╗
          ██╔══██╗██╔══██╗██╔════╝██╔════╝██║██╔══██╗╚██╗░██╔╝
          ██║░░╚═╝███████║╚█████╗░╚█████╗░██║██║░░██║░╚████╔╝░
          ██║░░██╗██╔══██║░╚═══██╗░╚═══██╗██║██║░░██║░░╚██╔╝░░
          ╚█████╔╝██║░░██║██████╔╝██████╔╝██║██████╔╝░░░██║░░░
          ░╚════╝░╚═╝░░╚═╝╚═════╝░╚═════╝░╚═╝╚═════╝░░░░╚═╝░░░
          
- hosts: AOSCX_Switches
  gather_facts : False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli  

  tasks:
  - name: Configure NTP server
    #community.network.aruba_config:
    aoscx_config:
      #lines: ntp server 1.1.1.1
      src:  ~/afne/configs/01-ntpcnfg.txt    # Relative path          