---
# With the use of the:
#
#            - import_playbook
#            - import_tasks
#
# directives, this playbook demonstrates another level of elegance to the 
# the modularity and practicality of reusable playbooks. The targeted 
# devices will be all four of the AOSCX switches.
#
# The playbook:
#              1) Generates a configuration file
#              2) Configures the targeted AOSCX switches
#              3) Saves the switches updated configuartions
#                 into seperate uniquely named text files.
#              4) Saves the running config on each switch
#                 (write memory)
#
# To run playbook use:
#
# $ ansible-playbook 19_rsble-plybk.yml -vvv
#

#-----------------------------------------------------------------------------

# Importing playbook that runs on the localhost

- name: Generate ntp configuration file
  import_playbook: ./playbooks/05_basicconfigs/15_local-ntp-cfg.yml
  #import_playbook: /home/ansible/afne/playbooks/05_basicconfigs/15_local-ntp-cfg.yml

# ----------------------------------------------------------------------------

- hosts: AOSCX_Switches
  gather_facts : False
  collections:
    - arubanetworks.aoscx
  vars:
    ansible_connection: network_cli

  tasks:

  - name: Config NTP server from the imported playbook generated file
    aoscx_config:  
      src: ~/afne/src/ntp-cnfig4.cfg   
      match: none
            
  # Utilizing the import_tasks directive

  - name: Save configuration to a text file
    import_tasks: ./tasks/01_tsk-cnfg-to-file.yml

  - name: Always save configurations, said my P.M. Roy
    import_tasks: ./tasks/02_tsk-sv-cnfg-wrt-mem.yml