---
# Playbook:
#
#     1) Retrieves the date-time-stamp from the local system
#     2) Stores the day of the week date-time-stamp
#     3) Creates a day of the week named sub-directory
#     4) Executes the "show run" command on switches
#     5) Saves the regestered variable "config" to a text file
#        with the name of the switch to the specified 
#        named day of the week directory.
#
# NOTE: The "aoscx_command" module is being used with "commands"
#       parameter to push the "show run" cli command on the switch.

- hosts: localhost

  tasks:
  - name: Get ansible date/time facts
    setup:
      filter: "ansible_date_time"
      gather_subset: "!all"

  - name: Store DTStamp as fact
    set_fact:
      DTStamp: "{{ ansible_date_time.weekday }}"

  - name: Create day of the week sub-directory date-time-stamp
    file:
     path: ~/afne/backups/{{hostvars.localhost.DTStamp}}
     state: directory
  run_once: true


- hosts: AOSCX_Switches
  gather_facts : False
  collections:
    - arubanetworks.aoscx
  
  tasks:  
  - name: Show_Run
    aoscx_command: 
      commands: show run
    register: config

  - name: Save config to sub-directory with day of the week date-time-stamp
    copy:
      content: "{{config.stdout[0]}}"
      dest: "~/afne/backups/{{hostvars.localhost.DTStamp}}/{{inventory_hostname}}-{{hostvars.localhost.DTStamp}}-config.txt"
